//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SCAT
{
    using System;
    using System.Collections.Generic;
    
    public partial class Call
    {
        public int IDCall { get; set; }
        public Nullable<int> IDBrigade { get; set; }
        public Nullable<int> IDDefects { get; set; }
        public Nullable<int> IDAddress { get; set; }
    
        public virtual Address Address { get; set; }
        public virtual Brigade Brigade { get; set; }
        public virtual Defects Defects { get; set; }
    }
}
