//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SCAT
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SCATEntities2 : DbContext
    {
        public SCATEntities2()
            : base("name=SCATEntities2")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Accountant> Accountant { get; set; }
        public virtual DbSet<Address> Address { get; set; }
        public virtual DbSet<Brigade> Brigade { get; set; }
        public virtual DbSet<Call> Call { get; set; }
        public virtual DbSet<Categories> Categories { get; set; }
        public virtual DbSet<Defects> Defects { get; set; }
        public virtual DbSet<Promotions> Promotions { get; set; }
        public virtual DbSet<Repairmans> Repairmans { get; set; }
        public virtual DbSet<Shutdown> Shutdown { get; set; }
        public virtual DbSet<Statement> Statement { get; set; }
        public virtual DbSet<Streets> Streets { get; set; }
        public virtual DbSet<Subscriber> Subscriber { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<Tariffs> Tariffs { get; set; }
    }
}
