//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SCAT
{
    using System;
    using System.Collections.Generic;
    
    public partial class Statement
    {
        public int IDStatement { get; set; }
        public Nullable<int> IDSubscriber { get; set; }
        public Nullable<int> IDTariffs { get; set; }
        public Nullable<int> IDPromotions { get; set; }
        public Nullable<System.DateTime> PaymentDate { get; set; }
        public Nullable<System.DateTime> PaymentEndDate { get; set; }
        public Nullable<int> IDAccountant { get; set; }

        public decimal? DiscountPrice { 
            get
            {
                if(Promotions != null)
                {
                    var percent = (Tariffs.Price.Value * Convert.ToDecimal(Promotions.Discount)) / 100;

                    return Tariffs.Price - percent;
                }
              

                return Tariffs.Price.Value;
            }
        }

    
        public virtual Accountant Accountant { get; set; }
        public virtual Promotions Promotions { get; set; }
        public virtual Subscriber Subscriber { get; set; }
        public virtual Tariffs Tariffs { get; set; }
    }
}
